/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jarvis' at '28.06.17 23:35' with Gradle 2.13
 *
 * @author Jarvis, @date 28.06.17 23:35
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
